# Generated by Django 5.2 on 2025-04-28 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('calories_burned', 'Calories Burned'), ('badges_collected', 'Badges Collected'), ('active_minutes', 'Active Minutes'), ('workouts_completed', 'Workouts Completed')], default='calories_burned', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'rank'],
                'unique_together': {('user', 'leaderboard_type', 'week_start')},
            },
        ),
    ]
