# Generated by Django 5.2 on 2025-04-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_workoutstat_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutstat',
            name='calories_burned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutstat',
            name='duration',
            field=models.IntegerField(blank=True, default=0, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='workoutstat',
            name='workout_type',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CompletedGoal',
        ),
    ]
