# Generated by Django 5.2 on 2025-04-27 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden'], name='social_post_is_hidd_a49ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['reports_count'], name='social_post_reports_0749d6_idx'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='social.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreport',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['post'], name='social_post_post_id_4606f6_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['reporter'], name='social_post_reporte_4d8c85_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['reason'], name='social_post_reason_16809e_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['is_resolved'], name='social_post_is_reso_6012d1_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['created_at'], name='social_post_created_1e15cd_idx'),
        ),
    ]
