# Generated by Django 5.2 on 2025-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_postreport_post_is_hidden_post_reports_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
