# Generated by Django 5.2 on 2025-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_following",
            field=models.BooleanField(
                default=True, help_text="Allow other users to follow me"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_email",
            field=models.BooleanField(
                default=False, help_text="Make email visible to other users"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_stats",
            field=models.BooleanField(
                default=True, help_text="Make workout statistics visible to other users"
            ),
        ),
    ]
