# Generated by Django 5.2 on 2025-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_ban_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics/'),
        ),
    ]
