# Generated by Django 5.2 on 2025-04-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-medal', max_length=50)),
                ('requirement_type', models.CharField(choices=[('workouts_completed', 'Workouts Completed'), ('calories_burned', 'Calories Burned'), ('active_minutes', 'Active Minutes'), ('streak_days', 'Streak Days'), ('special', 'Special Achievement')], max_length=50)),
                ('requirement_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['requirement_type', 'requirement_value'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_workout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.badge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user_profile', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(through='user.UserBadge', to='user.badge'),
        ),
    ]
