# Generated by Django 5.2 on 2025-04-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_badge_userprofile_last_workout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
