# Generated by Django 5.2 on 2025-04-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_initial_badges'),
        ('user', '0007_userprofile_is_profile_complete'),
    ]

    operations = [
    ]
